import { Merriweather  } from "next/font/google";
import "./globals.css";

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ['400', '700'],
});



export const metadata = {
  title: "¿Quien me gobierna?",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={merriweather.className}
      >
        {children}
      </body>
    </html>
  );
}
